services:
  mysql:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysqlvol:/var/lib/mysql
      - ./backup:/var/backup
    env_file:
      - .env
    ports:
      - "3307:3306"

  redis:
    image: redis
    volumes:
      - redisvol:/data
    ports:
      - "6379:6379"

  taxi-rider-api:
    build:
      context: .
      dockerfile: ./apps/rider-api/Dockerfile
    restart: always
    depends_on:
      - "mysql"
      - "redis"
      - "taxi-admin-api"
    volumes:
      - ./config-new:/app/config
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - "4000:3000"

  taxi-driver-api:
    build:
      context: .
      dockerfile: ./apps/driver-api/Dockerfile
    restart: always
    depends_on:
      - "mysql"
      - "redis"
      - "taxi-admin-api"
    volumes:
      - ./config-new:/app/config
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - "4002:3000"

  taxi-admin-api:
    build:
      context: .
      dockerfile: ./apps/admin-api/Dockerfile
    restart: always
    depends_on:
      - "mysql"
      - "redis"
    volumes:
      - ./config-new:/app/config
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - "4001:3000"

  admin-panel:
    build:
      context: ./apps/admin-frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4003:80"
    env_file:
      - ./apps/admin-frontend/.env.dev

  payment-gateways:
    build:
      context: ./apps/payment-gateways/Dockerfile
    depends_on:
      - "taxi-rider-api"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3333
    ports:
      - "3333:3333"

volumes:
  redisvol:
  mysqlvol:
  taxiassets: