services:
  mysql:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysqlvol:/var/lib/mysql
      - ./backup:/var/backup
    env_file:
      - .env
    ports:
      - "3307:3306"
  redis:
    image: redis
    volumes:
      - redisvol:/data
  taxi-rider-api:
    build:
      context: .
      dockerfile: ./apps/rider-api/Dockerfile
    restart: always
    depends_on:
      - "mysql"
      - "redis"
      - "taxi-admin-api"
    volumes:
      - ./config-new:/app/config
      - ./license-verify:/app/node_modules/license-verify
    env_file:
      - .env
    ports:
      - "4000:3000"
  taxi-driver-api:
    build:
      context: .
      dockerfile: ./apps/driver-api/Dockerfile
    restart: always
    depends_on:
      - "mysql"
      - "redis"
      - "taxi-admin-api"
    volumes:
      - ./config-new:/app/config
      - ./license-verify:/app/node_modules/license-verify
    env_file:
      - .env
    ports:
      - "4002:3000"
  taxi-admin-api:
    build:
      context: .
      dockerfile: ./apps/admin-api/Dockerfile
    restart: always
    depends_on:
      - "mysql"
      - "redis"
    volumes:
      - ./config-new:/app/config
      - ./license-verify:/app/node_modules/license-verify
    env_file:
      - .env
    ports:
      - "4001:3000"
  taxi-admin-panel:
    image: ghcr.io/lumeagency/taxi-legacy-admin-panel:4.0.4
    restart: always
    volumes:
      - taxiassets:/usr/share/nginx/html/assets
  payment-gateways:
    build:
      context: .
      dockerfile: ./apps/payment-gateways/Dockerfile
    depends_on:
      - "taxi-rider-api"
    ports:
      - "3333:3333"
    env_file:
      - .env

  nginx:
    image: nginx
    depends_on:
      - "payment-gateways"
      - "taxi-rider-api"
      - "taxi-driver-api"
      - "taxi-admin-api"
      - "taxi-admin-panel"
    volumes:
      - ./.nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./img:/app/uploads
    ports:
      - "80:80"
volumes:
  redisvol:
  mysqlvol:
  taxiassets:
