part of 'pricing_details.cubit.dart';

@freezed
sealed class PricingDetailsState with _$PricingDetailsState {
  const factory PricingDetailsState({
    String? pricingId,
    int? personCapacity,
    String? categoryId,
    int? searchRadius,
    @Default(0) int providerSharePercent,
    @Default(10000) int maximumDestinationDistance,
    Fragment$Media? image,
    String? name,
    String? description,
    List<Enum$TaxiOrderType>? orderTypes,
    @Default(0) double baseFare,
    @Default(0) double roundingFactor,
    @Default(0) double perHundredMeters,
    @Default(0) double perMinuteDrive,
    @Default(0) double perMinuteWait,
    @Default(0) double prepayPercent,
    @Default(0) double minimumFee,
    @Default(Enum$ServicePaymentMethod.CashCredit)
    Enum$ServicePaymentMethod paymentMethod,
    @Default(0) double cancellationTotalFee,
    @Default(0) double cancellationDriverShare,
    @Default(0) double providerShareFlat,
    @Default(false) bool twoWayAvailable,
    @Default(0) int displayPriority,
    @Default(Enum$PricingMode.FIXED) Enum$PricingMode pricingMode,
    @Default(Enum$RangePolicy.ENFORCE) Enum$RangePolicy rangePolicy,
    @Default(80) double priceRangeMinPercent,
    @Default(150) double priceRangeMaxPercent,
    @Default([]) List<Input$TimeMultiplierInput> timeMultipliers,
    @Default([]) List<Input$DistanceMultiplierInput> distanceMultipliers,
    @Default([]) List<Input$WeekdayMultiplierInput> weekdayMultipliers,
    @Default([]) List<Input$DateRangeMultiplierInput> dateRangeMultipliers,
    @Default([]) List<String> serviceOptionIds,
    @Default([]) List<Fragment$taxiOrderOption> options,
    @Default([]) List<Fragment$taxiPricingCategory> categories,
    @Default([]) List<Fragment$regionWithCategory> regions,
    @Default([]) List<String> selectedRegionIds,
    @Default(ApiResponseInitial()) ApiResponse<Query$taxiPricing?> remoteData,
    @Default(ApiResponseInitial()) ApiResponse<void> networkStateSave,
  }) = _PricingDetailsState;

  const PricingDetailsState._();

  Input$ServiceInput get toInput => Input$ServiceInput(
    personCapacity: personCapacity,
    categoryId: categoryId!,
    searchRadius: searchRadius ?? 0,
    providerSharePercent: providerSharePercent,
    maximumDestinationDistance: maximumDestinationDistance,
    mediaId: image!.id,
    orderTypes: orderTypes ?? [],
    name: name!,
    description: description,
    baseFare: baseFare,
    roundingFactor: roundingFactor,
    perHundredMeters: perHundredMeters,
    perMinuteDrive: perMinuteDrive,
    perMinuteWait: perMinuteWait,
    prepayPercent: prepayPercent / 100,
    minimumFee: minimumFee,
    paymentMethod: paymentMethod,
    cancellationTotalFee: cancellationTotalFee,
    cancellationDriverShare: cancellationDriverShare,
    providerShareFlat: providerShareFlat,
    twoWayAvailable: twoWayAvailable,
    displayPriority: displayPriority,
    pricingMode: pricingMode,
    rangePolicy: rangePolicy,
    priceRangeMinPercent: priceRangeMinPercent / 100,
    priceRangeMaxPercent: priceRangeMaxPercent / 100,
    timeMultipliers: timeMultipliers,
    distanceMultipliers: distanceMultipliers,
    weekdayMultipliers: weekdayMultipliers,
    dateRangeMultipliers: dateRangeMultipliers,
  );
}
