import { registerEnumType } from '@nestjs/graphql';

export enum EmailEventType {
  // Driver lifecycle
  DRIVER_APPROVED = 'DRIVER_APPROVED',
  DRIVER_REJECTED = 'DRIVER_REJECTED',
  DRIVER_DOCUMENTS_PENDING = 'DRIVER_DOCUMENTS_PENDING',
  DRIVER_SUSPENDED = 'DRIVER_SUSPENDED',
  DRIVER_REGISTRATION_SUBMITTED = 'DRIVER_REGISTRATION_SUBMITTED',

  // Order lifecycle
  ORDER_CONFIRMED = 'ORDER_CONFIRMED',
  ORDER_COMPLETED = 'ORDER_COMPLETED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  ORDER_REFUNDED = 'ORDER_REFUNDED',

  // Authentication
  AUTH_WELCOME = 'AUTH_WELCOME',
  AUTH_PASSWORD_RESET = 'AUTH_PASSWORD_RESET',
  AUTH_VERIFICATION = 'AUTH_VERIFICATION',

  // KYC Expiration Reminders
  EXPIRING_KYC_30_DAY_REMINDER = 'EXPIRING_KYC_30_DAY_REMINDER',
  EXPIRING_KYC_14_DAY_REMINDER = 'EXPIRING_KYC_14_DAY_REMINDER',
  EXPIRING_KYC_7_DAY_REMINDER = 'EXPIRING_KYC_7_DAY_REMINDER',
  EXPIRING_KYC_3_DAY_REMINDER = 'EXPIRING_KYC_3_DAY_REMINDER',
  EXPIRING_KYC_2_DAY_REMINDER = 'EXPIRING_KYC_2_DAY_REMINDER',
  EXPIRING_KYC_1_DAY_REMINDER = 'EXPIRING_KYC_1_DAY_REMINDER',
}

registerEnumType(EmailEventType, {
  name: 'EmailEventType',
  description: 'The type of event that triggers an email',
});
